"""Runner p27 — autoatenção emergente via dinâmica replicadora.

Verifica que g_t casa com softmax(β·t·f) (precisão de máquina), a
entropia colapsa para winner-take-all conforme βt cresce, e a ablação
da normalização glial faz os ganhos divergirem.

Checks that g_t matches softmax(β·t·f) (machine precision), entropy
collapses to winner-take-all as βt grows, and ablating the glial
normalization makes gains diverge.
"""

import argparse

import numpy as np

from .method import ReplicatorAttention, entropy, track_vs_theory

N = 8
SEEDS = list(range(8))
BETAS = [0.5, 1.0, 2.0]


def render(match, ent_rows, abl):
    lines = [
        "# RESULTS — p27 Emergent self-attention via replicator dynamics",
        "",
        "Generated by `python -m papers.p27_emergent_attention.run --write-results`"
        " (fixed seeds, offline, numpy only). Exponentiated replicator"
        " g_{t+1} = g·e^{βf}/Z with glial normalization Z.",
        "",
        "## g_t vs teoria softmax(βt·f) / exact match",
        "",
        "| β | max|g_30 − softmax| | argmax = best fitness |",
        "|---|---|---|",
    ]
    for b, (err, ok) in match.items():
        lines.append(f"| {b} | {err:.2e} | {ok:.2f} |")
    lines += [
        "",
        "## Colapso da entropia → winner-take-all (β=1, mean over seeds)",
        "",
        "| t | 0 | 5 | 10 | 20 | 30 |",
        "|---|---|---|---|---|---|",
        f"| H(g_t) | {ent_rows} |",
        "",
        "## Ablação da normalização glial / normalization ablation",
        "",
        "| variant | Σg após 30 passos |",
        "|---|---|",
        f"| com glia (Z = Σg·e^f) | {abl['glia']:.3f} |",
        f"| sem glia (Z = 1) | {abl['noglia']:.2e} |",
        "",
        "## Leitura / reading",
        "",
        "- A dinâmica replicadora local + normalização global da glia gera",
        "  exatamente a alocação softmax — 'atenção' emergente sem softmax",
        "  hard-coded (mesmo papel da normalização no p21).",
        "- Sem a normalização os ganhos explodem — a glia é a restrição do",
        "  simplex, não um detalhe de implementação.",
        "- Local replicator dynamics + global glial normalization yield",
        "  exactly the softmax allocation — emergent 'attention' with no",
        "  hard-coded softmax. Without it, gains diverge.",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    rng = np.random.default_rng(args.seed)
    match = {}
    for b in BETAS:
        errs, oks = [], []
        for s in SEEDS:
            f = np.random.default_rng(s).normal(0, 1, N)
            err, hist = track_vs_theory(f, b)
            errs.append(err[-1])
            oks.append(hist[-1].argmax() == np.argmax(f))
        match[b] = (float(np.mean(errs)), float(np.mean(oks)))
    ents = np.zeros(31)
    for s in SEEDS:
        f = np.random.default_rng(s).normal(0, 1, N)
        _, hist = track_vs_theory(f, 1.0)
        ents += np.array([entropy(g) for g in hist])
    ents /= len(SEEDS)
    ent_rows = " | ".join(f"{ents[t]:.2f}" for t in (0, 5, 10, 20, 30))
    f = rng.normal(0, 1, N)
    a_g = ReplicatorAttention(f, 1.0, glia=True)
    a_n = ReplicatorAttention(f, 1.0, glia=False)
    a_g.run(30)
    a_n.run(30)
    abl = {"glia": float(a_g.g.sum()), "noglia": float(a_n.g.sum())}
    md = render(match, ent_rows, abl)
    print(md)
    if args.write_results:
        import pathlib

        out = pathlib.Path(__file__).with_name("RESULTS.md")
        out.write_text(md + "\n")
        print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
