"""PT: experimento do p12_zep — grafo temporal no dataset conversacional
multi-persona vs baselines + oracle, com string de contexto bitemporal.

EN: p12_zep experiment — temporal graph on the multi-persona conversational
dataset vs baselines + oracle, with a bitemporal context string.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from papers.common.conv_data import generate
from papers.common.conv_eval import (
    EvalResult,
    baseline_rows,
    eval_memory,
    render_acc_table,
)
from papers.common.llm import LLM, get_llm
from papers.p12_zep.adapter import ZepAdapter


def experiment(seed: int, llm: LLM) -> tuple[list[EvalResult], str]:
    data = generate(seed)
    zep = ZepAdapter(llm)
    r = eval_memory(zep, data, llm, name="Zep (temporal graph)")
    r.extra = f"{len(zep.graph.edges)} edges"
    r2 = eval_memory(ZepAdapter(llm, use_mmr=True), data, llm,
                     name="Zep + MMR")
    rows = [r, r2, *baseline_rows(data, llm)]
    ctx = zep.graph.context("where does Pedro live", k=4)
    return rows, ctx


def render(rows: list[EvalResult], ctx: str) -> str:
    lines = ["# RESULTS — p12 Zep / Graphiti", "",
             "Generated by `python -m papers.p12_zep.run --write-results` "
             "(fixed seed, MockLLM). Demonstrates the mechanism offline — "
             "does NOT reproduce the paper's numbers.", ""]
    lines += render_acc_table(rows, extra_col="graph")
    lines += ["", "Example bitemporal context "
              "(`graph.context('where does Pedro live')`):", "",
              "```", ctx, "```"]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, seed=args.seed)
    rows, ctx = experiment(args.seed, llm)
    out = render(rows, ctx)
    print(out)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(out,
                                                          encoding="utf-8")


if __name__ == "__main__":
    main()
