"""PT: experimento do p12_zep — grafo temporal no dataset conversacional
vs baselines, com string de contexto bitemporal.

EN: p12_zep experiment — temporal graph on the conversational dataset vs
baselines, with bitemporal context strings.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from papers.common.conv_data import generate
from papers.common.llm import LLM, get_llm
from papers.common.memory_api import (
    BM25Memory,
    EmbeddingRAGMemory,
    FullContextMemory,
    MemoryItem,
)
from papers.common.reader import answer_with_evidence, judge_answer
from papers.p12_zep.adapter import ZepAdapter


@dataclass
class Row:
    setting: str
    accuracy: float


def _eval_mem(mem, data, llm: LLM, k: int = 8) -> float:
    for t in data.all_turns():
        mem.add(MemoryItem(t.text, t.ts))
    ok = sum(judge_answer(llm, q.question, q.gold,
                          answer_with_evidence(
                              llm, q.question, mem.retrieve(q.question, k=k)))
             for q in data.questions)
    return ok / len(data.questions)


def experiment(seed: int, llm: LLM) -> tuple[list[Row], str]:
    data = generate(seed)
    zep = ZepAdapter(llm)
    acc = _eval_mem(zep, data, llm)
    rows = [Row("Zep (temporal graph)", acc),
            Row("Zep + MMR", _eval_mem(ZepAdapter(llm, use_mmr=True), data,
                                       llm))]
    for name, m in [("FullContext (truncated)", FullContextMemory(200)),
                    ("BM25", BM25Memory()),
                    ("EmbeddingRAG", EmbeddingRAGMemory())]:
        rows.append(Row(name, _eval_mem(m, data, llm)))
    ctx = zep.graph.context("where does the user live", k=4)
    return rows, ctx


def render(rows: list[Row], ctx: str) -> str:
    lines = ["# RESULTS — p12 Zep / Graphiti", "",
             "Generated by `python -m papers.p12_zep.run --write-results` "
             "(fixed seed, MockLLM). Demonstrates the mechanism offline — "
             "does NOT reproduce the paper's numbers.", "",
             "| memory system | accuracy |", "|---|---|"]
    for r in rows:
        lines.append(f"| {r.setting} | {r.accuracy:.2f} |")
    lines += ["", "Example bitemporal context "
              "(`graph.context('where does the user live')`):", "",
              "```", ctx, "```"]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, seed=args.seed)
    rows, ctx = experiment(args.seed, llm)
    out = render(rows, ctx)
    print(out)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(out,
                                                          encoding="utf-8")


if __name__ == "__main__":
    main()
