"""PT: experimento do p15 — avalia TODOS os sistemas de memória do repo
+ oráculo nas 5 habilidades, em 2 comprimentos de história, e ablata os 4
knobs de design (§4.2) no baseline RAG.

EN: p15 experiment — evaluates ALL repo memory systems + oracle across the
5 abilities at 2 history lengths, and ablates the 4 design knobs (§4.2) on
the RAG baseline.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from papers.common.adapters import all_memory_systems
from papers.common.conv_data import ConvSet, generate
from papers.common.llm import LLM, get_llm
from papers.common.memory_api import FullContextMemory, MemoryItem
from papers.common.reader import answer_with_evidence, judge_answer
from papers.p15_longmemeval.method import (
    ABILITIES,
    ABILITY_ORDER,
    DesignRAG,
    load_official,
    scale_history,
)

RESULTS = Path(__file__).parent / "RESULTS.md"


@dataclass
class Row:
    name: str
    per_ability: dict[str, float] = field(default_factory=dict)
    overall: float = 0.0
    extra: str = ""


def _eval_system(mem, data: ConvSet, llm: LLM, k: int = 8) -> Row:
    if hasattr(mem, "add_session"):
        for s in data.sessions:
            mem.add_session(s)
    else:
        for t in data.all_turns():
            mem.add(MemoryItem(t.text, t.ts, {}))
    by: dict[str, list[int]] = {a: [] for a in ABILITY_ORDER}
    for q in data.questions:
        ab = next((a for a, qt in ABILITIES.items() if qt == q.qtype),
                  "IE")
        if hasattr(mem, "answer"):
            pred = mem.answer(llm, q.question, k=k)
        else:
            ev = mem.retrieve(q.question, k=k,
                              now=datetime(2025, 1, 1))
            pred = answer_with_evidence(llm, q.question, ev)
        by[ab].append(int(judge_answer(llm, q.question, q.gold, pred)))
    per = {a: (sum(v) / len(v) if v else 0.0) for a, v in by.items()}
    return Row("", per, sum(per.values()) / len(per))


def _table(rows: list[Row]) -> list[str]:
    hdr = ("| system | overall | " + " | ".join(ABILITY_ORDER) + " |")
    sep = "|---|" + "---|" * (len(ABILITY_ORDER) + 1)
    out = [hdr, sep]
    for r in rows:
        out.append(f"| {r.name} | {r.overall:.2f} | "
                   + " | ".join(f"{r.per_ability[a]:.2f}"
                               for a in ABILITY_ORDER) + " |")
    return out


def experiment(seed: int, llm: LLM, data: ConvSet | None = None):
    data = data or generate(seed, n_personas=5)
    long_data = scale_history(data, extra_filler=3, seed=seed)
    systems = all_memory_systems(llm, None)
    oracle = FullContextMemory(max_tokens=10 ** 9)
    rows_short: list[Row] = []
    for m in systems + [oracle]:
        m.reset()
        r = _eval_system(m, data, llm)
        r.name = getattr(m, "name", "oracle")
        if m is oracle:
            r.name = "FullContext (oracle, untruncated)"
        rows_short.append(r)
    rows_long: list[Row] = []
    for m in systems + [oracle]:
        m.reset()
        r = _eval_system(m, long_data, llm)
        r.name = getattr(m, "name", "oracle")
        if m is oracle:
            r.name = "FullContext (oracle, untruncated)"
        rows_long.append(r)
    # PT: ablação dos knobs de design no RAG (história longa).
    # EN: design-knob ablation on RAG (long history).
    abl: list[Row] = []
    cfgs = [
        ("RAG base (round)", {}),
        ("value=session", {"value": "session"}),
        ("value=facts", {"value": "facts"}),
        ("key expansion", {"key_expansion": True}),
        ("time-aware query", {"time_aware": True}),
        ("Chain-of-Note", {"chain_of_note": True}),
        ("facts+keys+TA+CoN", {"value": "facts", "key_expansion": True,
                              "time_aware": True, "chain_of_note": True}),
    ]
    for label, kw in cfgs:
        m = DesignRAG(**kw)
        for s in long_data.sessions:
            m.add_session(s)
        r = _eval_system(m, long_data, llm)
        r.name = f"RAG {label}"
        abl.append(r)
    return rows_short, rows_long, abl


def render(rows_short: list[Row], rows_long: list[Row],
           abl: list[Row], n_hist: tuple[int, int]) -> str:
    lines = ["# RESULTS — p15 LongMemEval", "",
             "Generated by `python -m papers.p15_longmemeval.run "
             "--write-results` (fixed seed, MockLLM). Demonstrates the "
             "mechanism offline — does NOT reproduce the paper's numbers.",
             "",
             "Abilities: IE=information extraction, MR=multi-session "
             "reasoning, TR=temporal reasoning, KU=knowledge update, "
             "ABS=abstention (§3).", "",
             f"## Short history ({n_hist[0]} turns)", "",
             *_table(rows_short), "",
             f"## Long history ({n_hist[1]} turns)", "",
             *_table(rows_long), "",
             "## Design-knob ablation on RAG (long history, §4.2)", "",
             *_table(abl), ""]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--data", default="",
                    help="optional official LongMemEval JSON path")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, args.seed)
    data = load_official(args.data) if args.data else None
    base = data or generate(args.seed, n_personas=5)
    n_short = len(base.all_turns())
    n_long = len(scale_history(base, 4, args.seed).all_turns())
    rows_short, rows_long, abl = experiment(args.seed, llm, data)
    out = render(rows_short, rows_long, abl, (n_short, n_long))
    print(out)
    if args.write_results:
        RESULTS.write_text(out, encoding="utf-8")


if __name__ == "__main__":
    main()
