"""PT: experimento do p17 — grava trajetórias MiniWeb, pergunta por
competência, compara truncated-history / plain-RAG / AgentRunbook-R /
AgentRunbook-C com orçamento de tokens + latência.

EN: p17 experiment — records MiniWeb trajectories, questions by competency,
compares truncated-history / plain-RAG / AgentRunbook-R / AgentRunbook-C
under a token budget + latency.
"""

from __future__ import annotations

import argparse
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path

from papers.common.llm import LLM, get_llm
from papers.p17_longmemeval_v2.method import (
    COMP_ORDER,
    AgentRunbookC,
    AgentRunbookR,
    PlainRAG,
    TruncatedHistory,
    answer,
    make_questions,
    record_trajectories,
    verdict,
)

RESULTS = Path(__file__).parent / "RESULTS.md"


@dataclass
class Row:
    name: str
    per_comp: dict[str, float] = field(default_factory=dict)
    overall: float = 0.0
    extra: str = ""


def experiment(seed: int, llm: LLM):
    trajs = record_trajectories(seed)
    qs = make_questions(trajs)
    n_steps = sum(len(t.steps) for t in trajs)
    with tempfile.TemporaryDirectory() as td:
        systems = [TruncatedHistory(), PlainRAG(), AgentRunbookR(),
                   AgentRunbookC(Path(td))]
        rows: list[Row] = []
        for m in systems:
            for t in trajs:
                m.add_traj(t)
            by: dict[str, list[int]] = {c: [] for c in COMP_ORDER}
            t0 = time.perf_counter()
            for q in qs:
                ev = m.gather(q.question)
                pred = answer(q, ev, llm)
                by[q.comp].append(int(verdict(llm, q, pred)))
            ms = (time.perf_counter() - t0) * 1000 / len(qs)
            per = {c: (sum(v) / len(v) if v else 0.0)
                   for c, v in by.items()}
            rows.append(Row(m.name, per, sum(per.values()) / len(per),
                            f"{ms:.1f} ms"))
    return rows, n_steps


def render(rows: list[Row], n_steps: int) -> str:
    lines = ["# RESULTS — p17 LongMemEval-V2", "",
             "Generated by `python -m papers.p17_longmemeval_v2.run "
             "--write-results` (fixed seed, MockLLM). Demonstrates the "
             "mechanism offline — does NOT reproduce the paper's numbers.",
             "",
             f"{n_steps} trajectory steps on MiniWeb (with noise steps and "
             "one unlinked-URL gotcha). Competencies: static state recall, "
             "dynamic tracking, workflow knowledge, environment gotchas, "
             "premise awareness (incl. false-premise rejection). Context "
             "gathering under a 300-token budget (§3.3).", "",
             "| system | overall | static | dynamic | workflow | gotcha | "
             "premise | latency/q |",
             "|---|---|---|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r.name} | {r.overall:.2f} | "
                     + " | ".join(f"{r.per_comp[c]:.2f}" for c in COMP_ORDER)
                     + f" | {r.extra} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, args.seed)
    rows, n_steps = experiment(args.seed, llm)
    out = render(rows, n_steps)
    print(out)
    if args.write_results:
        RESULTS.write_text(out, encoding="utf-8")


if __name__ == "__main__":
    main()
