"""Reflexion — experimento executável / runnable experiment.

PT: `python -m papers.p02_reflexion.run [--seed 0] [--llm mock|openai]
[--write-results]` — avalia Reflexion vs baseline (mesmo agente sem reflexão)
no HouseholdEnv e no mini setting de programação. Com --write-results grava
RESULTS.md nesta pasta.

EN: evaluates Reflexion vs a no-reflection baseline on HouseholdEnv and on the
mini programming setting. --write-results writes RESULTS.md in this folder.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from papers.common.llm import MockLLM, get_llm
from papers.envs.household import TASKS
from papers.p02_reflexion.method import ReflexionAgent, reflexion_code_loop
from papers.p02_reflexion.prompts import CODE_TASKS

SEEDS = (0, 1, 2, 3, 4, 5, 6, 7)


def run_experiment(seed: int, llm_kind: str) -> dict:
    """PT: executa o experimento e devolve as linhas das tabelas.

    EN: runs the experiment and returns table rows.
    """
    hh_rows = []
    for task in TASKS:
        cum_r = cum_b = p_r = p_b = n_r = n_b = 0
        for s in SEEDS:
            sseed = seed * 100 + s
            r = ReflexionAgent(get_llm(llm_kind, sseed)).run_task(task)
            b = ReflexionAgent(get_llm(llm_kind, sseed), use_reflection=False).run_task(task)
            cum_r += any(x.success for x in r)
            cum_b += any(x.success for x in b)
            p_r += sum(x.success for x in r[1:])
            n_r += len(r) - 1
            p_b += sum(x.success for x in b[1:])
            n_b += len(b) - 1
        n = len(SEEDS)
        hh_rows.append((task.task_id, task.task_type, task.variant,
                        f"{cum_r / n:.2f}", f"{cum_b / n:.2f}",
                        f"{p_r / max(n_r, 1):.2f}", f"{p_b / max(n_b, 1):.2f}"))

    code_rows = []
    for task in CODE_TASKS:
        wr = wb = 0
        for s in range(6):
            ok_r, _, _ = reflexion_code_loop(MockLLM(s), task, True)
            ok_b, _, _ = reflexion_code_loop(MockLLM(s), task, False)
            wr += ok_r
            wb += ok_b
        code_rows.append((task["name"], f"{wr}/6", f"{wb}/6"))
    return {"household": hh_rows, "code": code_rows}


def render(res: dict) -> str:
    out = ["# RESULTS — p02 Reflexion\n",
           "Generated by `python -m papers.p02_reflexion.run --write-results` "
           "(fixed seed, MockLLM). Demonstrates the mechanism offline — does NOT "
           "reproduce the paper's numbers. / Gerado por run.py com seed fixa "
           "(MockLLM) — demonstra o mecanismo offline, NÃO reproduz os números "
           "do paper.\n",
           "## Household (8 seeds, up to 4 trials per episode)\n",
           "Columns: `cum.` = cumulative success rate (any of the 4 trials); "
           "`post-1` = success rate in trials 2+ (after the first reflection). "
           "Post-1 is where verbal memory should help.\n",
           "| task | type | variant | Refl. cum. | base cum. | Refl. post-1 | base post-1 |",
           "|---|---|---|---|---|---|---|"]
    for row in res["household"]:
        out.append("| " + " | ".join(row) + " |")
    out += ["", "## Programming (tasks solved within 4 trials, 6 seeds)\n",
            "| function | Reflexion | baseline |", "|---|---|---|"]
    for row in res["code"]:
        out.append("| " + " | ".join(row) + " |")
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default=None, choices=["mock", "openai"])
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    res = run_experiment(args.seed, args.llm or "mock")
    text = render(res)
    print(text)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
