"""Reflexion — experimento executável / runnable experiment.

PT: `python -m papers.p02_reflexion.run [--seed 0] [--llm mock|openai]
[--write-results]` — avalia Reflexion vs baseline (mesmo agente sem reflexão)
no HouseholdEnv e no mini setting de programação. No setting de código, os
testes INTERNOS são derivados dos exemplos da docstring (task "code.tests") e
o sucesso real é pass@1 nos testes ESCONDIDOS — o paper discute falsos
positivos dos testes auto-gerados. Com --write-results grava RESULTS.md.

EN: evaluates Reflexion vs a no-reflection baseline on HouseholdEnv and on the
mini programming setting. Internal tests are derived from the docstring
examples only; true success is pass@1 on hidden tests (the paper discusses
internal-test false positives). --write-results writes RESULTS.md.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from pathlib import Path

from papers.common.llm import MockLLM, get_llm
from papers.envs.household import TASKS
from papers.p02_reflexion.method import ReflexionAgent, reflexion_code_loop
from papers.p02_reflexion.prompts import CODE_PROBLEMS

SEEDS = (0, 1, 2, 3, 4, 5, 6, 7)
CODE_SEEDS = 6


@dataclass
class CodeRow:
    """PT: linha da tabela de programação. EN: one programming-table row."""

    name: str
    refl_pass1: float     # pass@1 (hidden) com reflexão
    base_pass1: float     # pass@1 (hidden) sem reflexão
    internal_rate: float  # taxa de aprovação nos testes internos (Reflexion)
    false_pos: int        # interno passou, escondido falhou (Reflexion)


@dataclass
class ExperimentResult:
    household: list[tuple[str, str, str, str, str, str, str]]
    code: list[CodeRow] = field(default_factory=list)


def run_experiment(seed: int, llm_kind: str) -> ExperimentResult:
    """PT: executa o experimento e devolve as linhas das tabelas.

    EN: runs the experiment and returns table rows.
    """
    hh_rows = []
    for task in TASKS:
        cum_r = cum_b = p_r = p_b = n_r = n_b = 0
        for s in SEEDS:
            sseed = seed * 100 + s
            r = ReflexionAgent(get_llm(llm_kind, sseed)).run_task(task)
            b = ReflexionAgent(get_llm(llm_kind, sseed), use_reflection=False).run_task(task)
            cum_r += any(x.success for x in r)
            cum_b += any(x.success for x in b)
            p_r += sum(x.success for x in r[1:])
            n_r += len(r) - 1
            p_b += sum(x.success for x in b[1:])
            n_b += len(b) - 1
        n = len(SEEDS)
        hh_rows.append((task.task_id, task.task_type, task.variant,
                        f"{cum_r / n:.2f}", f"{cum_b / n:.2f}",
                        f"{p_r / max(n_r, 1):.2f}", f"{p_b / max(n_b, 1):.2f}"))

    code_rows: list[CodeRow] = []
    for prob in CODE_PROBLEMS:
        wr = wb = wi = fp = 0
        for s in range(CODE_SEEDS):
            r_r = reflexion_code_loop(MockLLM(s), prob, True)
            r_b = reflexion_code_loop(MockLLM(s), prob, False)
            wr += r_r.hidden_ok
            wb += r_b.hidden_ok
            wi += r_r.internal_ok
            fp += r_r.internal_ok and not r_r.hidden_ok
        code_rows.append(CodeRow(prob.name, wr / CODE_SEEDS, wb / CODE_SEEDS,
                                 wi / CODE_SEEDS, fp))
    return ExperimentResult(hh_rows, code_rows)


def render(res: ExperimentResult) -> str:
    out = ["# RESULTS — p02 Reflexion\n",
           "Generated by `python -m papers.p02_reflexion.run --write-results` "
           "(fixed seed, MockLLM). Demonstrates the mechanism offline — does NOT "
           "reproduce the paper's numbers. / Gerado por run.py com seed fixa "
           "(MockLLM) — demonstra o mecanismo offline, NÃO reproduz os números "
           "do paper.\n",
           "## Household (8 seeds, up to 4 trials per episode)\n",
           "Columns: `cum.` = cumulative success rate (any of the 4 trials); "
           "`post-1` = success rate in trials 2+ (after the first reflection). "
           "Post-1 is where verbal memory should help.\n",
           "| task | type | variant | Refl. cum. | base cum. | Refl. post-1 | base post-1 |",
           "|---|---|---|---|---|---|---|"]
    for row in res.household:
        out.append("| " + " | ".join(row) + " |")
    out += ["", f"## Programming (pass@1 on HIDDEN tests, {CODE_SEEDS} seeds)\n",
            "Internal tests are derived only from docstring examples "
            "(task `code.tests`). `FP` = cases that passed the internal tests "
            "but failed the hidden ones — the false positives the paper "
            "discusses (self-generated tests may not cover edge cases).\n",
            "| function | Reflexion pass@1 | baseline pass@1 | internal pass "
            "| internal→hidden FP |",
            "|---|---|---|---|---|"]
    for row in res.code:
        out.append(f"| {row.name} | {row.refl_pass1:.2f} | {row.base_pass1:.2f}"
                   f" | {row.internal_rate:.2f} | {row.false_pos} |")
    out += ["",
            "Internal-vs-hidden agreement is implied by `internal pass` vs "
            "`Reflexion pass@1`: identical rows mean the self-generated tests "
            "were sufficient; FP>0 rows show where they were not."]
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default=None, choices=["mock", "openai"])
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    res = run_experiment(args.seed, args.llm or "mock")
    text = render(res)
    print(text)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
