"""Runner p25 — AGMP: metaplasticidade vs esquecimento catastrófico.

Sequência de regressões lineares; mede a matriz (fase × tarefa) de MSE,
o esquecimento médio e o erro na tarefa nova. Astrócitos acumulam a
contribuição sináptica |grad·w| e fecham o gate de plasticidade
1/(1+κA): κ alto demais trava a rede (dilema estabilidade–plasticidade).

Sequence of linear regressions; measures the (phase × task) MSE matrix,
mean forgetting, and newest-task error. Astrocytes accumulate synaptic
contribution |grad·w| and close the plasticity gate 1/(1+κA): too-large
κ freezes the network (stability–plasticity dilemma).
"""

import argparse

import numpy as np

from .method import forgetting, make_tasks, plasticity, train_sequence

SEEDS = list(range(6))
KAPPAS = [0.0, 2.0, 5.0, 20.0, 50.0]


def render(mats, ksweep):
    lines = [
        "# RESULTS — p25 AGMP: astrocyte-gated metaplasticity",
        "",
        "Generated by `python -m papers.p25_agmp_continual.run --write-results`"
        " (fixed seeds, offline, numpy only). Sequential linear-regression"
        f" tasks T1→T2→T3, {len(SEEDS)} seeds. MSE matrix rows = phase,",
        "cols = task evaluated.",
        "",
    ]
    for name, M in mats.items():
        lines += [
            f"## {name}",
            "",
            "| after phase | T1 | T2 | T3 |",
            "|---|---|---|---|",
        ]
        for i, row in enumerate(M):
            lines.append(f"| T{i + 1} | {row[0]:.3f} | {row[1]:.3f} | {row[2]:.3f} |")
        lines += [
            f"| **forgetting** | **{forgetting(M):.3f}** | | |",
            f"| **new-task MSE** | | | **{plasticity(M):.3f}** |",
            "",
        ]
    lines += [
        "## Sweep do gate κ / κ sweep",
        "",
        "| κ | forgetting | new-task MSE | mean final MSE |",
        "|---|---|---|---|",
    ]
    for k, r in ksweep.items():
        lines.append(f"| {k} | {r['forget']:.3f} | {r['plasticity']:.3f} | {r['mean']:.3f} |")
    lines += [
        "",
        "## Leitura / reading",
        "",
        "- Sem gate a T1 é apagada ao aprender T2/T3 (forgetting ~23); com"
        " AGMP as sinapses importantes endurecem e o esquecimento cai.",
        "- κ=50 retém T1 mas já não aprende T3 direito — o custo do"
        " excesso de consolidação, o dilema do paper.",
        "- Without the gate T1 is overwritten (forgetting ~23); AGMP"
        " stiffens important synapses and forgetting drops, but κ too"
        " large blocks new learning — the paper's dilemma.",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    np.random.default_rng(args.seed)

    def avg(Ms):
        return np.mean(Ms, 0)

    mats = {
        "plain SGD (sem glia)": avg(
            [train_sequence(s, make_tasks(s), 0.0, agmp=False) for s in SEEDS]
        ),
        "AGMP κ=5": avg([train_sequence(s, make_tasks(s), 5.0) for s in SEEDS]),
    }
    ksweep = {}
    for k in KAPPAS:
        Ms = [train_sequence(s, make_tasks(s), k) for s in SEEDS]
        ksweep[k] = {
            "forget": float(np.mean([forgetting(M) for M in Ms])),
            "plasticity": float(np.mean([plasticity(M) for M in Ms])),
            "mean": float(np.mean([M[-1].mean() for M in Ms])),
        }
    md = render(mats, ksweep)
    print(md)
    if args.write_results:
        import pathlib

        out = pathlib.Path(__file__).with_name("RESULTS.md")
        out.write_text(md + "\n")
        print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
