"""PT: experimento do p16 — ingestão incremental por chunks, pergunta no
fim, tabela por competência (AR/TTL/LRU/SF) para todos os sistemas.

EN: p16 experiment — incremental chunked ingestion, question at the end,
per-competency table (AR/TTL/LRU/SF) across all systems.
"""

from __future__ import annotations

import argparse
import time
from dataclasses import dataclass, field
from pathlib import Path

from papers.common.adapters import all_memory_systems
from papers.common.llm import LLM, get_llm
from papers.common.memory_api import FullContextMemory
from papers.p16_memoryagentbench.method import (
    BenchSet,
    answer,
    generate,
    ingest,
    score,
)

RESULTS = Path(__file__).parent / "RESULTS.md"
COMPS = ["AR", "TTL", "LRU", "SF"]


@dataclass
class Row:
    name: str
    per_comp: dict[str, float] = field(default_factory=dict)
    overall: float = 0.0
    extra: str = ""


def _eval(mem, bench: BenchSet, llm: LLM, k: int = 10) -> Row:
    by: dict[str, list[float]] = {c: [] for c in COMPS}
    t0 = time.perf_counter()
    for item in bench.items:
        mem.reset()
        ingest(mem, item.stream)
        pred = answer(mem, item, llm, k=k)
        by[item.comp].append(score(llm, item, pred))
    ms = (time.perf_counter() - t0) * 1000 / len(bench.items)
    per = {c: (sum(v) / len(v) if v else 0.0) for c, v in by.items()}
    return Row("", per, sum(per.values()) / len(per), f"{ms:.1f} ms")


def experiment(seed: int, llm: LLM) -> tuple[list[Row], int]:
    bench = generate(seed)
    systems = all_memory_systems(llm, None)
    oracle = FullContextMemory(max_tokens=10 ** 9)
    trunc = FullContextMemory(max_tokens=220)
    rows: list[Row] = []
    for m in systems + [trunc, oracle]:
        r = _eval(m, bench, llm)
        name = getattr(m, "name", "?")
        if m is oracle:
            name = "FullContext (oracle, untruncated)"
        elif m is trunc:
            name = "FullContext (truncated)"
        r.name = name
        rows.append(r)
    return rows, len(bench.items)


def render(rows: list[Row], n_items: int) -> str:
    lines = ["# RESULTS — p16 MemoryAgentBench", "",
             "Generated by `python -m papers.p16_memoryagentbench.run "
             "--write-results` (fixed seed, MockLLM). Demonstrates the "
             "mechanism offline — does NOT reproduce the paper's numbers.",
             "",
             f"{n_items} cases, incremental chunked ingestion, question at "
             "the end. Competencies: AR=accurate retrieval, TTL=test-time "
             "learning, LRU=long-range understanding (keyword coverage), "
             "SF=selective forgetting (§3.1).", "",
             "| system | overall | AR | TTL | LRU | SF | latency/item |",
             "|---|---|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r.name} | {r.overall:.2f} | "
                     + " | ".join(f"{r.per_comp[c]:.2f}" for c in COMPS)
                     + f" | {r.extra} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, args.seed)
    rows, n = experiment(args.seed, llm)
    out = render(rows, n)
    print(out)
    if args.write_results:
        RESULTS.write_text(out, encoding="utf-8")


if __name__ == "__main__":
    main()
