"""Runner p24 — memória situacional: gating por contexto e latch glial.

Duas medidas: (1) recall correto por (cue, contexto) — situação-gated vs
Hebbian plano que mistura contextos; (2) persistência contextual: a glia
faz latch do contexto na codificação e sustenta o recall quando a pista
contextual é removida por um intervalo.

Two measures: (1) correct recall per (cue, context) — situation-gated vs
flat Hebbian mixing contexts; (2) context persistence: glia latches the
context at encoding and sustains recall after the contextual cue is
removed for a gap.
"""

import argparse

import numpy as np

from .method import SituationMemory, context_persistence, gated_vs_flat

SEEDS = list(range(8))
GAPS = [0.0, 1.0, 2.0, 4.0, 8.0]
TAUS = [0.5, 2.0, 8.0]


def render(gated, flat, pers):
    lines = [
        "# RESULTS — p24 Situation-based neuromorphic memory",
        "",
        "Generated by `python -m papers.p24_situation_memory.run --write-results`"
        " (fixed seeds, offline, numpy only). Situation units gate cue→response"
        f" binding by context; a slow glial variable latches the context, "
        f"{len(SEEDS)} seeds.",
        "",
        "## Recall correto por (cue, contexto) / gated vs flat",
        "",
        "| model | cos(resposta, y correto) |",
        "|---|---|",
        f"| situation-gated (glia) | {gated:.3f} |",
        f"| flat Hebbian (sem contexto) | {flat:.3f} |",
        "",
        "## Persistência contextual — recall após remover a pista",
        "",
        "cos médio vs gap sem o vetor de contexto (a memória depende do",
        "latch glial; τ_ctx = escala de retenção da glia):",
        "",
        "| gap (s) | " + " | ".join(f"τ={t}" for t in TAUS) + " |",
        "|---|" + "---|" * len(TAUS),
    ]
    for gi, gap in enumerate(GAPS):
        row = " | ".join(f"{pers[(t, gi)]:.3f}" for t in TAUS)
        lines.append(f"| {gap} | {row} |")
    lines += [
        "",
        "## Leitura / reading",
        "",
        "- O mesmo cue mapeia para respostas diferentes por contexto; o"
        " Hebbian plano mistura as duas (~0.55) enquanto o gating"
        " situacional recupera a correta (~0.9).",
        "- Com a pista contextual removida, o recall sobrevive a gaps da"
        " ordem de τ_ctx — a glia segura a situação corrente; τ_ctx"
        " pequeno esquece rápido.",
        "- Same cue → different responses per context; flat Hebbian mixes"
        " them while the situation gate retrieves the right one. With the"
        " contextual cue removed, recall survives gaps on the order of"
        " τ_ctx — glia holds the current situation.",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    np.random.default_rng(args.seed)
    gs, fs = [], []
    for s in SEEDS:
        g, f = gated_vs_flat(SituationMemory(seed=s))
        gs.append(g)
        fs.append(f)
    gated, flat = float(np.mean(gs)), float(np.mean(fs))
    pers = {}
    for t in TAUS:
        for gi, gap in enumerate(GAPS):
            cs = [context_persistence(SituationMemory(seed=s, tau_ctx=t), gap) for s in SEEDS]
            pers[(t, gi)] = float(np.mean(cs))
    md = render(gated, flat, pers)
    print(md)
    if args.write_results:
        import pathlib

        out = pathlib.Path(__file__).with_name("RESULTS.md")
        out.write_text(md + "\n")
        print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
