"""p20 — experimento executável / runnable experiment.

PT: `python -m papers.p20_astrocyte_context.run [--seed 0]
[--write-results]` — reversão contextual A→B→C (3 ciclos, 30 trials por
fase): o mapa-alvo de B é a reversão exata de A. Compara sem astrócitos,
com astrócitos (restauração gateada pelo sinal de contexto) e a ablação
sem sinal de contexto. Métrica: |erro| médio dos 4 primeiros trials de
cada fase — o custo de readaptação após a troca de contexto.

EN: see PT. Contextual reversal A→B→C (3 cycles, 30 trials per phase):
context B's target map is the exact reversal of A. Compares no-astrocyte,
astrocyte (context-gated restoration) and the no-context-signal ablation.
Metric: mean |error| over the first 4 trials of each phase — the
re-adaptation cost after a context switch.
"""

from __future__ import annotations

import argparse
import statistics
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from papers.p20_astrocyte_context.method import (
    ContextGatedNet,
    make_targets,
    run_sequence,
)

RESULTS = Path(__file__).parent / "RESULTS.md"
CONTEXTS = ["A", "B", "C"]
CYCLES = 3
TRIALS_PER_PHASE = 30
SEEDS = range(8)


@dataclass
class ExperimentResult:
    # PT: método → lista por posição de fase → média dos erros iniciais.
    early: dict[str, list[float]] = field(default_factory=dict)
    first: dict[str, float] = field(default_factory=dict)   # fases 0–2
    reexp: dict[str, float] = field(default_factory=dict)   # fases 3+


def _run_method(seed: int, name: str, net_kwargs: dict) -> list[float]:
    rng = np.random.default_rng(seed)
    targets = make_targets(rng, CONTEXTS)
    seq = CONTEXTS * CYCLES
    net = ContextGatedNet(CONTEXTS, **net_kwargs)
    early = run_sequence(net, targets, seq, TRIALS_PER_PHASE, rng)
    return [statistics.mean(e) for e in early]


def run_experiment(seed: int) -> ExperimentResult:
    res = ExperimentResult()
    methods = [
        ("no astrocytes", {"eta_r": 0.0}),
        ("astrocytes (context-gated)", {}),
        ("astrocytes, no context signal", {"context_signal": False}),
    ]
    for name, kw in methods:
        per_seed = [_run_method(seed * 100 + s, name, kw) for s in SEEDS]
        res.early[name] = [statistics.mean(col) for col in zip(*per_seed,
                                                             strict=True)]
        res.first[name] = statistics.mean(res.early[name][:3])
        res.reexp[name] = statistics.mean(res.early[name][3:])
    return res


def render(res: ExperimentResult) -> str:
    seq = CONTEXTS * CYCLES
    out = ["# RESULTS — p20 Contextually-Guided Astrocyte Dynamics\n",
           "Generated by `python -m papers.p20_astrocyte_context.run "
           "--write-results` (fixed seed, offline, numpy only). "
           "Demonstrates the mechanism — does NOT reproduce the paper's "
           "numbers.\n",
           f"Reversal sequence {'→'.join(seq)}, {TRIALS_PER_PHASE} "
           "trials/phase, context B = exact reversal of A; cell = mean "
           f"|error| of the first 4 trials after the switch, over "
           f"{len(list(SEEDS))} seeds.\n",
           "## Early-phase |error| after each context switch\n",
           "| phase | " + " | ".join(f"{c}{i // 3 + 1}"
                                    for i, c in enumerate(seq)) + " |",
           "|---|" + "---|" * len(seq)]
    for name, row in res.early.items():
        out.append("| " + name + " | " + " | ".join(f"{v:.2f}" for v in row)
                   + " |")
    out += ["", "## Aggregated\n",
            "| method | first exposures (phases 1–3) | re-exposures "
            "(phases 4–9) |", "|---|---|---|"]
    for name in res.early:
        out.append(f"| {name} | {res.first[name]:.2f} | "
                   f"{res.reexp[name]:.2f} |")
    out += ["", "On first exposure all methods are alike (nothing is "
            "consolidated yet); on re-exposure the astrocyte restores the "
            "context's consolidated trace, cutting the re-adaptation "
            "error roughly in half, while a shared, ungated trace "
            "(no context signal) loses the benefit — the paper's own "
            "caveat that the network receives contextual information."]
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    text = render(run_experiment(args.seed))
    print(text)
    if args.write_results:
        RESULTS.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
