"""PT: experimento do p11_a_mem — A-MEM no dataset conversacional
multi-persona vs baselines + oracle; reporta links e evoluções de vizinhos.

EN: p11_a_mem experiment — A-MEM on the multi-persona conversational
dataset vs baselines + oracle; reports links and neighbor evolutions.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from papers.common.conv_data import generate
from papers.common.conv_eval import (
    EvalResult,
    baseline_rows,
    eval_memory,
    render_acc_table,
)
from papers.common.llm import LLM, get_llm
from papers.p11_a_mem.adapter import AMemAdapter


def experiment(seed: int, llm: LLM) -> list[EvalResult]:
    data = generate(seed)
    amem = AMemAdapter(llm)
    r = eval_memory(amem, data, llm, name="A-MEM")
    r.extra = f"{amem.mem.n_links} links / {amem.mem.n_evolutions} evolutions"
    return [r, *baseline_rows(data, llm)]


def render(rows: list[EvalResult]) -> str:
    lines = ["# RESULTS — p11 A-MEM", "",
             "Generated by `python -m papers.p11_a_mem.run --write-results` "
             "(fixed seed, MockLLM). Demonstrates the mechanism offline — "
             "does NOT reproduce the paper's numbers.", ""]
    lines += render_acc_table(rows, extra_col="graph events")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, seed=args.seed)
    out = render(experiment(args.seed, llm))
    print(out)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(out,
                                                          encoding="utf-8")


if __name__ == "__main__":
    main()
