"""PT: experimento do p11_a_mem — A-MEM no dataset conversacional vs
baselines (FullContext truncado, BM25, EmbeddingRAG), com métrica qa.judge.

EN: p11_a_mem experiment — A-MEM on the conversational dataset vs the 3
baselines, judged by qa.judge.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from papers.common.conv_data import generate
from papers.common.llm import LLM, get_llm
from papers.common.memory_api import (
    BM25Memory,
    EmbeddingRAGMemory,
    FullContextMemory,
    MemoryItem,
)
from papers.common.reader import answer_with_evidence, judge_answer
from papers.p11_a_mem.adapter import AMemAdapter


@dataclass
class Row:
    setting: str
    accuracy: float
    n_links: int
    n_evolutions: int


def _eval(mem, data, llm: LLM, k: int = 8) -> float:
    for t in data.all_turns():
        mem.add(MemoryItem(t.text, t.ts))
    ok = sum(judge_answer(llm, q.question, q.gold,
                          answer_with_evidence(
                              llm, q.question, mem.retrieve(q.question, k=k)))
             for q in data.questions)
    return ok / len(data.questions)


def experiment(seed: int, llm: LLM) -> list[Row]:
    data = generate(seed)
    amem = AMemAdapter(llm)
    acc = _eval(amem, data, llm)
    rows = [Row("A-MEM", acc, amem.mem.n_links, amem.mem.n_evolutions)]
    for name, m in [("FullContext (truncated)", FullContextMemory(200)),
                    ("BM25", BM25Memory()),
                    ("EmbeddingRAG", EmbeddingRAGMemory())]:
        rows.append(Row(name, _eval(m, data, llm), 0, 0))
    return rows


def render(rows: list[Row]) -> str:
    lines = ["# RESULTS — p11 A-MEM", "",
             "Generated by `python -m papers.p11_a_mem.run --write-results` "
             "(fixed seed, MockLLM). Demonstrates the mechanism offline — "
             "does NOT reproduce the paper's numbers.", "",
             "| memory system | accuracy | links created | neighbor evolutions |",
             "|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r.setting} | {r.accuracy:.2f} | {r.n_links} | "
                     f"{r.n_evolutions} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, seed=args.seed)
    out = render(experiment(args.seed, llm))
    print(out)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(out,
                                                          encoding="utf-8")


if __name__ == "__main__":
    main()
