"""PT: experimento do p13_mem0 — Mem0/Mem0g no dataset conversacional vs
baselines, com latência e tokens-em-contexto por query (métricas do paper).

EN: p13_mem0 experiment — Mem0/Mem0g on the conversational dataset vs
baselines, reporting latency and tokens-in-context per query.
"""

from __future__ import annotations

import argparse
import time
from dataclasses import dataclass
from pathlib import Path

from papers.common.conv_data import generate
from papers.common.llm import LLM, get_llm
from papers.common.memory_api import (
    BM25Memory,
    EmbeddingRAGMemory,
    FullContextMemory,
    MemoryItem,
)
from papers.common.reader import answer_with_evidence, judge_answer
from papers.p13_mem0.adapter import Mem0Adapter, Mem0gAdapter


@dataclass
class Row:
    setting: str
    accuracy: float
    ops: str
    mean_latency_ms: float
    mean_tokens_in: float


def _eval(mem, data, llm: LLM, k: int = 8) -> tuple[float, float, float]:
    for t in data.all_turns():
        mem.add(MemoryItem(t.text, t.ts))
    lat, tok = [], []
    ok = 0
    for q in data.questions:
        t0 = time.perf_counter()
        ev = mem.retrieve(q.question, k=k)
        lat.append(time.perf_counter() - t0)
        tok.append(len(q.question.split()) + sum(len(e.split()) for e in ev))
        ok += judge_answer(llm, q.question, q.gold,
                           answer_with_evidence(llm, q.question, ev))
    mean_lat = sum(lat) / len(lat) * 1000
    mean_tok = sum(tok) / len(tok)
    return ok / len(data.questions), mean_lat, mean_tok


def experiment(seed: int, llm: LLM) -> list[Row]:
    data = generate(seed)
    rows: list[Row] = []
    for label, ad in [("Mem0", Mem0Adapter(llm)),
                      ("Mem0g", Mem0gAdapter(llm))]:
        acc, lat, tok = _eval(ad, data, llm)
        s = ad.mem.stats
        ops = (f"A{s.adds}/U{s.updates}/D{s.deletes}/N{s.noops}"
               if not hasattr(ad.mem, "edges") else
               f"edges {len(ad.mem.edges)} (invalid {ad.mem.invalidated})")
        rows.append(Row(label, acc, ops, lat, tok))
    for name, m in [("FullContext (truncated)", FullContextMemory(200)),
                    ("BM25", BM25Memory()),
                    ("EmbeddingRAG", EmbeddingRAGMemory())]:
        acc, lat, tok = _eval(m, data, llm)
        rows.append(Row(name, acc, "-", lat, tok))
    return rows


def render(rows: list[Row]) -> str:
    lines = ["# RESULTS — p13 Mem0", "",
             "Generated by `python -m papers.p13_mem0.run --write-results` "
             "(fixed seed, MockLLM). Demonstrates the mechanism offline — "
             "does NOT reproduce the paper's numbers.", "",
             "| memory system | accuracy | ops (ADD/UPDATE/DELETE/NOOP or "
             "graph) | mean latency (ms/query) | mean tokens-in-context |",
             "|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r.setting} | {r.accuracy:.2f} | {r.ops} | "
                     f"{r.mean_latency_ms:.2f} | {r.mean_tokens_in:.1f} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, seed=args.seed)
    out = render(experiment(args.seed, llm))
    print(out)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(out,
                                                          encoding="utf-8")


if __name__ == "__main__":
    main()
