"""PT: experimento do p13_mem0 — Mem0/Mem0g no dataset conversacional
multi-persona vs baselines + oracle; reporta latência e
tokens-em-contexto por query (métricas do paper).

EN: p13_mem0 experiment — Mem0/Mem0g on the multi-persona conversational
dataset vs baselines + oracle; reports latency and tokens-in-context per
query (the paper's metrics).
"""

from __future__ import annotations

import argparse
import time
from pathlib import Path

from papers.common.conv_data import generate
from papers.common.conv_eval import (
    EvalResult,
    render_acc_table,
)
from papers.common.llm import LLM, get_llm
from papers.common.memory_api import (
    BM25Memory,
    EmbeddingRAGMemory,
    FullContextMemory,
    MemoryItem,
)
from papers.common.reader import answer_with_evidence, judge_answer
from papers.p13_mem0.adapter import Mem0Adapter, Mem0gAdapter


def _eval_timed(mem, data, llm: LLM, name: str, k: int = 8) -> EvalResult:
    """PT: como eval_memory mas mede latência e tokens-in-context por query.
    EN: like eval_memory but measures latency and tokens-in-context."""
    for t in data.all_turns():
        mem.add(MemoryItem(t.text, t.ts))
    lat, tok = [], []
    ok: dict[str, list[int]] = {}
    for q in data.questions:
        t0 = time.perf_counter()
        ev = mem.retrieve(q.question, k=k)
        lat.append(time.perf_counter() - t0)
        tok.append(len(q.question.split()) + sum(len(e.split()) for e in ev))
        ok.setdefault(q.qtype, []).append(
            int(judge_answer(llm, q.question, q.gold,
                             answer_with_evidence(llm, q.question, ev))))
    allv = [v for vs in ok.values() for v in vs]
    r = EvalResult(name, sum(allv) / len(allv),
                   {qt: (sum(vs) / len(vs) if vs else 0.0)
                    for qt, vs in ok.items()})
    r.extra = (f"{sum(lat) / len(lat) * 1000:.2f} ms / "
               f"{sum(tok) / len(tok):.0f} tok")
    return r


def experiment(seed: int, llm: LLM) -> list[EvalResult]:
    data = generate(seed)
    rows = []
    for label, ad in [("Mem0", Mem0Adapter(llm)),
                      ("Mem0g", Mem0gAdapter(llm))]:
        r = _eval_timed(ad, data, llm, label)
        s = ad.mem.stats
        ops = (f"A{s.adds}/U{s.updates}/D{s.deletes}/N{s.noops}; "
               if not hasattr(ad.mem, "edges") else
               f"{len(ad.mem.edges)} edges ({ad.mem.invalidated} invalid); ")
        r.extra = ops + r.extra
        rows.append(r)
    for name, m in [("FullContext (oracle, untruncated)",
                     FullContextMemory(100_000)),
                    ("FullContext (truncated)", FullContextMemory(200)),
                    ("BM25", BM25Memory()),
                    ("EmbeddingRAG", EmbeddingRAGMemory())]:
        rows.append(_eval_timed(m, data, llm, name))
    return rows


def render(rows: list[EvalResult]) -> str:
    lines = ["# RESULTS — p13 Mem0", "",
             "Generated by `python -m papers.p13_mem0.run --write-results` "
             "(fixed seed, MockLLM). Demonstrates the mechanism offline — "
             "does NOT reproduce the paper's numbers.", ""]
    lines += render_acc_table(rows, extra_col="ops / latency / tokens")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, seed=args.seed)
    out = render(experiment(args.seed, llm))
    print(out)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(out,
                                                          encoding="utf-8")


if __name__ == "__main__":
    main()
