"""CER — experimento executável / runnable experiment.

PT: `python -m papers.p05_cer.run [--seed 0] [--llm mock|openai]
[--write-results]` — avalia ReAct vs ReAct+CER nos 3 settings do paper
(offline, online, híbrido — Fig. 1) mais as ablações dynamics-only/skills-only
(§5.7) no MiniWeb. O buffer offline é destilado de trajetórias fornecidas
(inclui a pegadinha da página /git/admin não linkada — só alcançável via URL
na memória de dynamics).

EN: evaluates ReAct vs ReAct+CER under the paper's 3 settings plus
dynamics-only / skills-only ablations (§5.7) on MiniWeb. The offline buffer is
distilled from provided trajectories (including the unlinked /git/admin
gotcha — only reachable via a dynamics-memory URL).
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from pathlib import Path

from papers.common.llm import LLM, get_llm
from papers.envs.web import BASE, TASKS, MiniWeb
from papers.p05_cer.method import (
    ExperienceBuffer,
    distill,
    run_episode,
    run_online,
)

ONLINE_ROUNDS = 3

# PT: trajetórias OFFLINE fornecidas (stage A da Fig. 1) — scripts de ações
# executados deterministicamente no env. Inclui a visita ao /git/admin
# (URL não linkada — a "pegadinha" que a memória de dynamics resolve).
# EN: provided OFFLINE trajectories (stage A of Fig. 1) — action scripts run
# deterministically in the env, including the unlinked /git/admin visit.
OFFLINE_SCRIPTS: list[list[str]] = [
    [f"goto {BASE}/shop/search", "type in_q laptop", "click lnk_item_laptop",
     "stop $999"],
    [f"goto {BASE}/git/admin", "stop Admin Dashboard"],
    [f"goto {BASE}/forum/login", "type in_user demo", "type in_pass demo",
     f"goto {BASE}/forum/topic/t1", "type in_reply hello", "stop 3"],
    [f"goto {BASE}/shop/search", "type in_q keyboard",
     "click lnk_item_keyboard", "click btn_add_cart",
     f"goto {BASE}/shop/cart", "stop 1"],
]


def _scripted_trajectory(actions: list[str]) -> list[tuple[str, str]]:
    """PT: executa o script no env e devolve (ação, observação).

    EN: runs the script in the env and returns (action, observation) pairs.
    """
    env = MiniWeb(TASKS[0])
    env.reset()
    traj = []
    for a in actions:
        res = env.step(a)
        traj.append((a, res.observation))
        if res.done:
            break
    return traj


def build_offline_buffer(llm: LLM) -> ExperienceBuffer:
    """PT: destila as trajetórias fornecidas no buffer (setting offline).

    EN: distills the provided trajectories into the buffer (offline setting).
    """
    buf = ExperienceBuffer()
    for script in OFFLINE_SCRIPTS:
        distill(llm, buf, _scripted_trajectory(script))
    return buf


def _masked(buf: ExperienceBuffer, keep_dyn: bool,
            keep_skl: bool) -> ExperienceBuffer:
    """PT: cópia do buffer com um tipo desligado (ablação §5.7).
    EN: buffer copy with one type disabled (§5.7 ablation)."""
    b = ExperienceBuffer()
    b.dynamics = dict(buf.dynamics) if keep_dyn else {}
    b.skills = dict(buf.skills) if keep_skl else {}
    return b


@dataclass
class ExperimentResult:
    rates: dict[str, float | list[float]] = field(default_factory=dict)
    dyn_entries: list[str] = field(default_factory=list)
    skill_names: list[str] = field(default_factory=list)
    skill_example: str = ""


def run_experiment(seed: int, llm_kind: str) -> ExperimentResult:
    llm = get_llm(llm_kind, seed)
    res = ExperimentResult()
    # baseline: sem memória
    res.rates["ReAct (no memory)"] = sum(
        run_episode(llm, t).success for t in TASKS) / len(TASKS)
    # offline
    off = build_offline_buffer(llm)
    res.rates["CER offline"] = sum(
        run_episode(llm, t, off).success for t in TASKS) / len(TASKS)
    # online: 3 rounds, começa vazio
    rates, _buf = run_online(llm, TASKS, ONLINE_ROUNDS)
    res.rates["CER online (r1→r3)"] = rates
    # híbrido: começa do buffer offline
    rates_h, _bufh = run_online(llm, TASKS, ONLINE_ROUNDS, off)
    res.rates["CER hybrid (r1→r3)"] = rates_h
    # ablações (offline)
    res.rates["CER offline — dynamics only"] = sum(
        run_episode(llm, t, _masked(off, True, False)).success
        for t in TASKS) / len(TASKS)
    res.rates["CER offline — skills only"] = sum(
        run_episode(llm, t, _masked(off, False, True)).success
        for t in TASKS) / len(TASKS)
    res.dyn_entries = sorted(off.dynamics.values())
    res.skill_names = sorted(off.skills)
    res.skill_example = next(iter(off.skills.values()), "")
    return res


def render(res: ExperimentResult) -> str:
    out = ["# RESULTS — p05 CER\n",
           "Generated by `python -m papers.p05_cer.run --write-results` "
           "(fixed seed, MockLLM). Demonstrates the mechanism offline — does "
           "NOT reproduce the paper's numbers.\n",
           "Note: task w03 (hidden /git/admin page) is only solvable when the "
           "dynamics memory provides the unlinked URL.\n",
           "| setting | success rate |", "|---|---|"]
    for name, r in res.rates.items():
        if isinstance(r, list):
            out.append(f"| {name} | "
                       + " → ".join(f"{x:.2f}" for x in r) + " |")
        else:
            out.append(f"| {name} | {r:.2f} |")
    out += ["", "## Distilled dynamics (offline buffer)\n", "| url — usage |",
            "|---|"]
    for d in res.dyn_entries:
        out.append(f"| {d} |")
    out += ["", "## Distilled skills (offline buffer)\n",
            "```",
            res.skill_example or "(none)",
            "```",
            "Skills in buffer: " + ", ".join(res.skill_names)]
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default=None, choices=["mock", "openai"])
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    res = run_experiment(args.seed, args.llm or "mock")
    text = render(res)
    print(text)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(text,
                                                         encoding="utf-8")


if __name__ == "__main__":
    main()
