"""Runner p31 — evidência de futilidade → passividade.

Três regimes: fútil (p=0), viável ruidoso (p=0.3) e fases (fútil→viável→
fútil). Sem acumulador o agente desperdiça todas as tentativas no regime
fútil; com glia ele suprime o comportamento — e mantém a maioria dos
acertos no regime viável, ao custo de falsos positivos ocasionais.

Three regimes: futile (p=0), noisy-viable (p=0.3) and phases
(futile→viable→futile). Without the accumulator the agent wastes every
attempt in the futile regime; with glia it suppresses behavior — while
keeping most wins in the viable regime, at the cost of occasional false
positives.
"""

import argparse

import numpy as np

from .method import make_schedule, run

SEEDS = list(range(10))
REGIMES = ["futile", "viable", "phases"]


def render(res):
    lines = [
        "# RESULTS — p31 Glia accumulate futility evidence (Mu 2019)",
        "",
        "Generated by `python -m papers.p31_futility_passivity.run --write-results`"
        " (fixed seeds, offline, numpy only). Abstract model of the"
        " biological finding — glial evidence accumulator suppresses"
        f" behavior after enough futile attempts. T=400, {len(SEEDS)} seeds.",
        "",
        "| regime | model | attempts | wins | passive periods |",
        "|---|---|---|---|---|",
    ]
    for name in REGIMES:
        for glia in (False, True):
            r = res[(name, glia)]
            m = "with glia" if glia else "no glia"
            lines.append(
                f"| {name} | {m} | {r['att']:.0f} | {r['wins']:.0f} | {r['pas']:.0f} |"
            )
    lines += [
        "",
        "## Leitura / reading",
        "",
        "- Regime fútil: sem glia o agente tenta as 400 vezes e não ganha",
        "  nada; com glia, após ~2/5 do tempo o comportamento é suprimido.",
        "- Regime viável (p=0.3): a glia mantém a maioria dos acertos —",
        "  sequências longas de falhas disparam passividade ocasional",
        "  (o custo da sensibilidade).",
        "- Futile regime: no-glia wastes all 400 attempts; glia suppresses",
        "  behavior after enough failures. Viable regime keeps most wins,",
        "  with occasional passivity from unlucky streaks — the",
        "  sensitivity cost.",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    np.random.default_rng(args.seed)
    res = {}
    for name in REGIMES:
        sch = make_schedule(name)
        for glia in (False, True):
            rs = [run(s, sch, glia) for s in SEEDS]
            res[(name, glia)] = {
                "att": float(np.mean([r[0] for r in rs])),
                "wins": float(np.mean([r[1] for r in rs])),
                "pas": float(np.mean([r[2] for r in rs])),
            }
    md = render(res)
    print(md)
    if args.write_results:
        import pathlib

        out = pathlib.Path(__file__).with_name("RESULTS.md")
        out.write_text(md + "\n")
        print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
