"""PT: experimento do p07_muse_autoskill — SkillsBench-lite + ciclo de vida.

EN: p07_muse_autoskill experiment — SkillsBench-lite + lifecycle.

Settings (comparação honesta / honest comparison):
- no-skills: baseline sem biblioteca — resposta trivial (devolve o input).
- skills-without-lifecycle: cria e usa skills mas SEM gate de teste, SEM
  refine, SEM merge, SEM prune.
- full-lifecycle: create → test-gate → use → memory → evaluate → refine →
  merge near-duplicates → prune low-utility (§4.3).

SkillsBench-lite: 12 tarefas pequenas, várias compartilhando skills
reutilizáveis (reverse ×2, vowels ×2, sum ×2, uppercase ×2).
"""

from __future__ import annotations

import argparse
import tempfile
from dataclasses import dataclass
from pathlib import Path

from papers.common.llm import LLM, get_llm, task_prompt
from papers.p07_muse_autoskill import prompts  # noqa: F401  (registra handlers)
from papers.p07_muse_autoskill.method import (
    KEEP_FIRST,
    KEEP_LAST,
    ContextDAG,
    SkillStore,
)


@dataclass
class Task:
    desc: str
    arg: str
    gold: str


# PT: 12 tarefas pequenas; várias dividem skills reutilizáveis. EN: 12 small
# tasks; several share reusable skills.
BENCH: list[Task] = [
    Task("reverse the string", "hello", "olleh"),
    Task("count vowels in the text", "banana", "3"),
    Task("sum the comma list", "1,2,3", "6"),
    Task("uppercase the text", "abc", "ABC"),
    Task("reverse the string", "world", "dlrow"),
    Task("count vowels in the text", "sky", "0"),
    Task("sort the comma list", "3,1,2", "1,2,3"),
    Task("max of the comma list", "4,9,2", "9"),
    Task("repeat the word n times", "ab*3", "ababab"),
    Task("count words in the sentence", "the cat sat", "3"),
    Task("sum the comma list", "4,5", "9"),
    Task("uppercase the text", "xy", "XY"),
]


@dataclass
class Row:
    setting: str
    success: float
    n_skills: int
    merged: int
    pruned: int


def _run_setting(llm: LLM, mode: str, workdir: Path) -> Row:
    store = SkillStore(workdir / mode, lifecycle=(mode != "no-lifecycle"))
    # PT: sementes para demonstrar merge/prune: uma duplicata e uma inútil.
    # EN: seeds to demo merge/prune: a duplicate and a useless skill.
    store.create(llm, "reverse the string")
    store.create(llm, "reverse a string please")
    store.create(llm, "unused placeholder skill")
    ok_n = 0
    for t in BENCH:
        sel = llm.complete(task_prompt(
            "muse.select",
            f"Task: {t.desc}\nCatalog:\n{store.catalog() or '- none'}")).strip()
        sd = store.skills.get(sel)
        if sd is None:
            sd = store.create(llm, t.desc)
        if sd is None:
            sd = store.create(llm, t.desc)  # PT: gate falhou → tenta de novo.
        if sd is None:
            continue
        # PT: disclosure progressivo — SKILL.md completo só após escolher.
        # EN: progressive disclosure — full SKILL.md only after selection.
        _ = store.full_doc(sd.name)
        ok, out = store.use(llm, sd.name, t.desc, t.arg)
        if not ok:
            if store.refine(llm, sd.name, t.desc, out):
                ok, out = store.use(llm, sd.name, t.desc, t.arg)
        ok_n += ok and out == t.gold
    store.merge_near_duplicates()
    store.prune_low_utility()
    return Row(mode, ok_n / len(BENCH), len(store.skills),
               store.merged, store.pruned)


def _no_skills() -> Row:
    ok = sum(t.arg == t.gold for t in BENCH)
    return Row("no-skills", ok / len(BENCH), 0, 0, 0)


def _dag_demo(llm: LLM) -> tuple[int, int]:
    dag = ContextDAG()
    dag.add(KEEP_FIRST, "system: you are a skill-using agent.")
    for i in range(6):
        dag.add(f"history_{i}", "step " + "x " * 40)
    dag.add(KEEP_LAST, "current task: uppercase the text")
    before = dag.total_tokens()
    dag.compress(llm, budget=60)
    return before, dag.total_tokens()


def experiment(seed: int, llm: LLM) -> tuple[list[Row], tuple[int, int]]:
    rows = [_no_skills()]
    with tempfile.TemporaryDirectory(prefix="muse_autoskill_") as td:
        rows.append(_run_setting(llm, "no-lifecycle", Path(td)))
        rows.append(_run_setting(llm, "full-lifecycle", Path(td)))
    return rows, _dag_demo(llm)


def render(rows: list[Row], dag: tuple[int, int]) -> str:
    lines = ["# RESULTS — p07 MUSE-Autoskill", "",
             "Generated by `python -m papers.p07_muse_autoskill.run "
             "--write-results` (fixed seed, MockLLM). Demonstrates the "
             "mechanism offline — does NOT reproduce the paper's numbers.",
             "",
             "SkillsBench-lite: 12 small tasks, several sharing reusable "
             "skills. Skill dirs are created under a temp run dir (not "
             "committed).", "",
             "| setting | success | skills left | merged | pruned |",
             "|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r.setting} | {r.success:.2f} | {r.n_skills} | "
                     f"{r.merged} | {r.pruned} |")
    lines += ["", "## Context DAG compression (Level-1 → Level-2)", "",
              f"tokens before → after budget-60 compression: "
              f"{dag[0]} → {dag[1]} (KEEP_FIRST/KEEP_LAST pinned)."]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, seed=args.seed)
    rows, dag = experiment(args.seed, llm)
    out = render(rows, dag)
    print(out)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(out,
                                                          encoding="utf-8")


if __name__ == "__main__":
    main()
