"""p19 — experimento executável / runnable experiment.

PT: `python -m papers.p19_astrocyte_assoc.run [--seed 0] [--write-results]`
— varre a carga P/N comparando Hopfield (K=1, só sinapses) com modelos
neurônio–astrócito de ordens K∈{2,3,5} (mais sinapses por astrócito ⇒
interações de ordem maior) e a leitura suave softmax(β·m) — o caso limite
Transformer. Tabelas: recuperação vs carga, recuperação a carga fixa vs N
(a escala supralinear do paper) e o efeito da temperatura β (cosseno
médio, mostrando a transição leitura suave→winner-take-all).

EN: see PT. Sweeps memory load P/N comparing Hopfield (K=1, synapses
only) with neuron–astrocyte models of orders K∈{2,3,5} (more synapses per
astrocyte ⇒ higher-order interactions) and the soft softmax(β·m) readout
— the Transformer limiting case. Tables: recall vs load, recall at fixed
load vs N (the paper's supralinear scaling), and the β temperature effect
(mean cosine, showing the soft→winner-take-all transition).
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from papers.p19_astrocyte_assoc.method import capacity_sweep

RESULTS = Path(__file__).parent / "RESULTS.md"
N = 64
LOADS = [0.1, 0.2, 0.4, 0.6, 0.8, 1.0]
SIZES = [32, 64, 128]
TRIALS = 12

METHODS = [
    ("Hopfield (K=1, no astrocytes)", {"order": 1}),
    ("astrocytes K=2", {"order": 2}),
    ("astrocytes K=3", {"order": 3}),
    ("astrocytes K=5", {"order": 5}),
]


@dataclass
class ExperimentResult:
    capacity: dict[str, list[float]] = field(default_factory=dict)
    scaling: dict[str, list[float]] = field(default_factory=dict)
    betas: dict[str, list[float]] = field(default_factory=dict)


def run_experiment(seed: int) -> ExperimentResult:
    res = ExperimentResult()
    rng = np.random.default_rng(seed)
    for name, kw in METHODS:
        res.capacity[name], _ = capacity_sweep(rng, N, LOADS, trials=TRIALS,
                                             **kw)
    # PT: escala a carga fixa 0.5 — a vantagem supralinear aparece quando
    # N cresce. EN: fixed-load-0.5 scaling as N grows.
    for name, kw in METHODS:
        res.scaling[name] = [
            capacity_sweep(rng, n, [0.5], trials=TRIALS, **kw)[0][0]
            for n in SIZES]
    # PT: transição suave→duro ao subir β (cosseno médio).
    # EN: soft→hard transition with β (mean cosine).
    for beta in (2.0, 8.0, 32.0):
        _, res.betas[f"β={beta:g}"] = capacity_sweep(
            rng, N, [0.4, 0.8], order=3, beta=beta, trials=TRIALS)
    return res


def render(res: ExperimentResult) -> str:
    out = ["# RESULTS — p19 Neuron-Astrocyte Associative Memory\n",
           "Generated by `python -m papers.p19_astrocyte_assoc.run "
           "--write-results` (fixed seed, offline, numpy only). "
           "Demonstrates the mechanism — does NOT reproduce the paper's "
           "numbers.\n",
           f"N={N} neurons, cues with 30% of bits flipped, ≤30 update "
           "steps, success = final |cosine| ≥ 0.8; each cell = recall "
           f"fraction over {TRIALS} trials.\n",
           "## Recall vs memory load\n",
           "| load P/N | " + " | ".join(f"{ld:g}" for ld in LOADS) + " |",
           "|---|" + "---|" * len(LOADS)]
    for name, row in res.capacity.items():
        out.append("| " + name + " | " + " | ".join(f"{v:.2f}" for v in row)
                   + " |")
    out += ["", "## Recall at load 0.5 vs network size\n",
            "| N | " + " | ".join(str(n) for n in SIZES) + " |",
            "|---|" + "---|" * len(SIZES)]
    for name, row in res.scaling.items():
        out.append("| " + name + " | " + " | ".join(f"{v:.2f}" for v in row)
                   + " |")
    out += ["", "## Softmax-readout temperature (mean |cosine|)\n",
            "| load | 0.4 | 0.8 |", "|---|---|---|"]
    for name, row in res.betas.items():
        out.append("| " + name + " | " + " | ".join(f"{v:.2f}" for v in row)
                   + " |")
    out += ["", "Hopfield collapses beyond ~0.2·N stored patterns while "
            "astrocyte-mediated higher-order models keep retrieving at "
            "several-fold higher load, and the gap widens with N — the "
            "mechanism behind the paper's supralinear capacity claim. "
            "The β-sweep shows the soft softmax readout approaching the "
            "hard winner-take-all limit (the Transformer correspondence)."]
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    text = render(run_experiment(args.seed))
    print(text)
    if args.write_results:
        RESULTS.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
