"""PT: experimento do p09_generative_agents — difusão de informação na
Mini-Smallville + ablações (sem reflexão, sem planejamento), como no paper.

EN: p09_generative_agents experiment — information diffusion in
Mini-Smallville + ablations (no reflection, no planning), paper-style.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from papers.common.llm import LLM, get_llm
from papers.p09_generative_agents.method import run_simulation

TICKS = 12


@dataclass
class Row:
    setting: str
    final_aware: int
    spread_tick: int   # PT: 1º tick com todos sabendo (0=nunca). EN: first all-aware.
    curve: list[int]


def experiment(seed: int, llm: LLM) -> list[Row]:
    rows = []
    for name, plan, refl in [("full", True, True),
                             ("no-reflection", True, False),
                             ("no-planning", False, True),
                             ("neither", False, False)]:
        curve = run_simulation(llm, TICKS, plan, refl, seed)
        spread = next((i for i, c in enumerate(curve) if c == 4), 0)
        rows.append(Row(name, curve[-1], spread, curve))
    return rows


def render(rows: list[Row]) -> str:
    lines = ["# RESULTS — p09 Generative Agents", "",
             "Generated by `python -m papers.p09_generative_agents.run "
             "--write-results` (fixed seed, MockLLM). Demonstrates the "
             "mechanism offline — does NOT reproduce the paper's numbers.",
             "",
             "Mini-Smallville: 4 agents, hourly ticks. Agent 0 learns about "
             "the party at tick 0; we measure how the information diffuses.",
             "",
             "| setting | aware at end | all-aware at tick | curve |",
             "|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r.setting} | {r.final_aware}/4 | {r.spread_tick} | "
                     f"{' '.join(map(str, r.curve))} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, seed=args.seed)
    rows = experiment(args.seed, llm)
    out = render(rows)
    print(out)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(out,
                                                          encoding="utf-8")


if __name__ == "__main__":
    main()
