"""MemRL — experimento executável / runnable experiment.

PT: `python -m papers.p03_memrl.run [--seed 0] [--llm mock|openai]
[--write-results]` — 4 épocas sobre as tarefas do HouseholdEnv. A cada episódio:
Fase A+B recuperam memórias → política age → recompensa atualiza Q (MC) das
memórias injetadas → resumo vira nova tripla. Baselines: sem memória e RAG por
similaridade (λ=0). Ablações de λ e k1/k2 + correlação Q×sucesso.

EN: see PT. Runs 4 epochs over HouseholdEnv tasks; reports MemRL vs no-memory
vs similarity-only RAG (λ=0), λ and k1/k2 ablations, and the learned-Q ×
success correlation.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from papers.common.llm import get_llm, task_prompt
from papers.envs.household import TASKS, run_episode
from papers.p03_memrl.method import MemRLMemory
from papers.p03_memrl.prompts import SEED_MEMORIES

EPOCHS = 4


def run_one_epoch(llm_kind: str, seed: int, mem: MemRLMemory | None,
                  lam_override: float | None = None) -> float:
    """PT: uma época = um episódio por tarefa; devolve a taxa de sucesso.

    EN: one epoch = one episode per task; returns success rate.
    """
    wins = 0
    for task in TASKS:
        llm = get_llm(llm_kind, seed)
        mem_lines, idx = ([], [])
        if mem is not None:
            mem_lines, idx = mem.retrieve(task.description)
        res = run_episode(llm, task, memory_lines=mem_lines)
        wins += res["success"]
        if mem is not None:
            # PT: MC update só nas memórias injetadas + nova tripla do resumo.
            # EN: MC update on injected memories only + new triplet from summary.
            mem.update(idx, 1.0 if res["success"] else 0.0)
            body = ("Summarize the trajectory into a short reusable experience.\n"
                    f"Intent: {task.description}\n"
                    "Outcome: " + ("success" if res["success"] else "failure") + "\n"
                    + "\n".join(o.split(" You are in")[0] for _, o in res["trajectory"]))
            e_new = llm.complete(task_prompt("memrl.summarize", body))
            mem.add(task.description, e_new)
    return wins / len(TASKS)


def run_experiment(seed: int, llm_kind: str) -> dict:
    res: dict = {}
    for name, lam in (("MemRL (λ=0.5)", 0.5), ("RAG similarity (λ=0)", 0.0),
                      ("No memory", None)):
        mem = None if lam is None else MemRLMemory(lam=lam)
        if mem:
            for z, e in SEED_MEMORIES:
                mem.add(z, e)
        rates = [run_one_epoch(llm_kind, seed * 100 + ep, mem)
                 for ep in range(EPOCHS)]
        res[name] = rates
    # Ablações de λ (como a Fig. 5 do paper) e k1/k2.
    abl = {}
    for lam in (0.0, 0.25, 0.5, 0.75, 1.0):
        mem = MemRLMemory(lam=lam)
        for z, e in SEED_MEMORIES:
            mem.add(z, e)
        abl[f"λ={lam}"] = [run_one_epoch(llm_kind, seed * 100 + ep, mem)
                           for ep in range(EPOCHS)]
    for k1, k2 in ((2, 1), (4, 2), (8, 4)):
        mem = MemRLMemory(lam=0.5, k1=k1, k2=k2)
        for z, e in SEED_MEMORIES:
            mem.add(z, e)
        abl[f"k1={k1},k2={k2}"] = [run_one_epoch(llm_kind, seed * 100 + ep, mem)
                                   for ep in range(EPOCHS)]
    res["abl"] = abl
    # Correlação Q × sucesso: Q final das memórias úteis vs distratoras.
    mem = MemRLMemory()
    for z, e in SEED_MEMORIES:
        mem.add(z, e)
    for ep in range(EPOCHS):
        run_one_epoch(llm_kind, seed * 100 + ep, mem)
    res["q_items"] = sorted(((t.q, t.e[:60]) for t in mem.items), reverse=True)[:8]
    return res


def render(res: dict) -> str:
    out = ["# RESULTS — p03 MemRL\n",
           "Generated by `python -m papers.p03_memrl.run --write-results` "
           "(fixed seed, MockLLM). Demonstrates the mechanism offline — does NOT "
           "reproduce the paper's numbers.\n",
           "## Success rate per epoch (HouseholdEnv)\n",
           "| method | e1 | e2 | e3 | e4 |", "|---|---|---|---|---|"]
    for name, rates in res.items():
        if name in ("abl", "q_items"):
            continue
        out.append("| " + name + " | " + " | ".join(f"{r:.2f}" for r in rates) + " |")
    out += ["", "## Ablations (per-epoch success rate)\n",
            "| setting | e1 | e2 | e3 | e4 |", "|---|---|---|---|---|"]
    for name, rates in res["abl"].items():
        out.append("| " + name + " | " + " | ".join(f"{r:.2f}" for r in rates) + " |")
    out += ["", "## Learned Q-values (top of the bank after 4 epochs)\n",
            "| Q | experience |", "|---|---|"]
    for q, e in res["q_items"]:
        out.append(f"| {q:.2f} | {e} |")
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default=None, choices=["mock", "openai"])
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    res = run_experiment(args.seed, args.llm or "mock")
    text = render(res)
    print(text)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
