"""p21 — experimento executável / runnable experiment.

PT: `python -m papers.p21_astrocyte_transformer.run [--seed 0]
[--write-results]` — verifica numericamente a correspondência do paper:
a dinâmica neurônio–astrócito converge para softmax(QKᵀ/√d)·V. Tabelas:
erro final vs referência por escala temporal τ_a (o astrócito lento dita
o tempo de convergência), iterações até erro < 1e−6, e a ablação sem
normalização (A≡1 = atenção linear não normalizada).

EN: see PT. Numerically verifies the paper's correspondence: the
neuron–astrocyte dynamics converge to softmax(QKᵀ/√d)·V. Tables: final
error vs reference per astrocyte timescale τ_a (the slow astrocyte sets
convergence time), iterations to error < 1e−6, and the unnormalized
ablation (A≡1 = linear attention).
"""

from __future__ import annotations

import argparse
import statistics
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from papers.p21_astrocyte_transformer.method import (
    NeuronAstrocyteAttention,
    attention_scores,
    softmax_ref,
)

RESULTS = Path(__file__).parent / "RESULTS.md"
TAUS = [1.0, 10.0, 50.0]
SEEDS = range(8)


@dataclass
class ExperimentResult:
    final_err: dict[str, float] = field(default_factory=dict)
    iters: dict[str, int] = field(default_factory=dict)
    ablation: dict[str, float] = field(default_factory=dict)
    profile: dict[str, list[float]] = field(default_factory=dict)


def run_experiment(seed: int) -> ExperimentResult:
    res = ExperimentResult()
    for tau in TAUS:
        errs, it = [], []
        for s in SEEDS:
            rng = np.random.default_rng(seed * 100 + s)
            scores, values = attention_scores(rng)
            att = NeuronAstrocyteAttention(tau_a=tau)
            y, w, hist = att.run(scores, values)
            ref = softmax_ref(scores) @ values
            errs.append(float(np.abs(y - ref).max()))
            it.append(len(hist))
        res.final_err[f"τ_a={tau:g}"] = statistics.mean(errs)
        res.iters[f"τ_a={tau:g}"] = int(statistics.mean(it))
    for astro in (True, False):
        errs = []
        for s in SEEDS:
            rng = np.random.default_rng(seed * 100 + s)
            scores, values = attention_scores(rng)
            att = NeuronAstrocyteAttention(astrocyte=astro)
            y, _, _ = att.run(scores, values)
            ref = softmax_ref(scores) @ values
            errs.append(float(np.abs(y - ref).max()))
        res.ablation["with astrocyte" if astro
                     else "ablated (A≡1, linear attn)"] = statistics.mean(
                         errs)
    # PT: perfil de convergência — erro máx dos pesos vs iteração.
    # EN: convergence profile — max weight error vs iteration.
    rng = np.random.default_rng(seed)
    scores, _ = attention_scores(rng)
    for tau in TAUS:
        _, _, hist = NeuronAstrocyteAttention(tau_a=tau).run(
            scores, np.eye(len(scores)))
        res.profile[f"τ_a={tau:g}"] = hist
    return res


def render(res: ExperimentResult) -> str:
    out = ["# RESULTS — p21 Building Transformers from Neurons and "
           "Astrocytes\n",
           "Generated by `python -m papers.p21_astrocyte_transformer.run "
           "--write-results` (fixed seed, offline, numpy only). "
           "Demonstrates the proposed computational correspondence — a "
           "mechanism result, not a benchmark.\n",
           "Random q, K, V (d=8, 10 keys, 6 values); the ODE integrates "
           "fast neuron units holding scores s=q·k/√d plus a slow "
           "astrocyte pooling total activity for divisive normalization. "
           f"Errors = max |output − softmax(s)·V| over "
           f"{len(list(SEEDS))} seeds.\n",
           "## Convergence vs astrocyte timescale\n",
           "| τ_a | final max |err| | iterations to <1e-6 |",
           "|---|---|---|"]
    for k in res.final_err:
        out.append(f"| {k} | {res.final_err[k]:.2e} | {res.iters[k]} |")
    out += ["", "## Ablation — the astrocyte IS the softmax denominator\n",
            "| variant | final max |err| vs softmax attention |",
            "|---|---|"]
    for k, v in res.ablation.items():
        out.append(f"| {k} | {v:.2e} |")
    out += ["", "## Convergence profile (max weight error per ~200 steps)\n",
            "| iter | " + " | ".join(k for k in res.profile) + " |",
            "|---|" + "---|" * len(res.profile)]
    longest = max(len(h) for h in res.profile.values())
    step = 200
    for i in range(0, longest, step):
        row = [f"{h[i]:.1e}" if i < len(h) else "—"
               for h in res.profile.values()]
        out.append(f"| {i} | " + " | ".join(row) + " |")
    out += ["", "The dynamics converge to machine-precision softmax "
            "attention; slower astrocytes (larger τ_a) only stretch the "
            "transient — the glial pooling supplies the normalization "
            "denominator, exactly the role the paper proposes. With the "
            "astrocyte ablated the output is unnormalized linear "
            "attention and no longer matches softmax."]
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    text = render(run_experiment(args.seed))
    print(text)
    if args.write_results:
        RESULTS.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
