"""PT: experimento do p08_coala — agente CoALA vs ReAct no HouseholdEnv.

EN: p08_coala experiment — CoALA agent vs plain ReAct on HouseholdEnv.

O agente CoALA roda TRIALS episódios por tarefa: entre episódios, internal
actions escrevem na LTM (episodic + semantic); dentro do episódio, o ciclo é
reason (WM) → retrieve (LTM) → propose→evaluate→select → execute (external).
O baseline ReAct usa o mesmo env/política sem memória nem ciclo interno.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from papers.common.llm import LLM, get_llm
from papers.envs.household import TASKS
from papers.p08_coala.method import CoALAAgent, run_react
from papers.p08_coala.taxonomy import render_table

TRIALS = 3
SEEDS = 5


@dataclass
class Row:
    setting: str
    success: float
    late_success: float  # PT: sucesso nos últimos trials. EN: late trials.


def experiment(seed: int, llm: LLM) -> list[Row]:
    # PT: baseline ReAct — um episódio por task×seed, sem memória.
    # EN: ReAct baseline — one episode per task×seed, no memory.
    ok = 0
    n = 0
    for t in TASKS:
        for s in range(SEEDS):
            r = run_react(llm, t, seed=seed * 100 + s)
            ok += r.success
            n += 1
    base = Row("ReAct (no memory)", ok / n, ok / n)

    # PT: CoALA — TRIALS episódios por task, LTM persiste entre eles.
    # EN: CoALA — TRIALS episodes per task, LTM persists across them.
    all_ok = late_ok = 0
    for t in TASKS:
        for s in range(SEEDS):
            agent = CoALAAgent(llm, seed=seed * 100 + s)
            succ = []
            for _ in range(TRIALS):
                r = agent.run_episode(t)
                succ.append(r.success)
            all_ok += sum(succ)
            late_ok += succ[-1]
    coala = Row("CoALA agent", all_ok / (len(TASKS) * SEEDS * TRIALS),
                late_ok / (len(TASKS) * SEEDS))
    return [base, coala]


def render(rows: list[Row]) -> str:
    lines = ["# RESULTS — p08 CoALA", "",
             "Generated by `python -m papers.p08_coala.run --write-results` "
             "(fixed seed, MockLLM). Demonstrates the mechanism offline — "
             "does NOT reproduce the paper's numbers.", "",
             "## Demo: HouseholdEnv", "",
             "| setting | mean success | last-trial success |",
             "|---|---|---|"]
    for r in rows:
        lines.append(f"| {r.setting} | {r.success:.2f} | "
                     f"{r.late_success:.2f} |")
    lines += ["", "## CoALA taxonomy of the repo (p01–p18)", "",
              render_table()]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, seed=args.seed)
    rows = experiment(args.seed, llm)
    out = render(rows)
    print(out)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(out,
                                                          encoding="utf-8")


if __name__ == "__main__":
    main()
