"""PT: experimento do p10_memgpt — MemGPT no dataset conversacional.

EN: p10_memgpt experiment — MemGPT on the conversational dataset.

Ingere as 4 sessões (fatos → atualizações → retratação → enchimento) e
responde às perguntas com archival+recall; compara com os 3 baselines via
qa.judge. Mostra contagens de warning/flush (70%/100%) e chamadas.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from papers.common.conv_data import generate
from papers.common.llm import LLM, get_llm
from papers.common.memory_api import MemoryItem
from papers.common.reader import answer_with_evidence, judge_answer
from papers.p10_memgpt.method import FUNCTIONS, MemGPTAgent


@dataclass
class Row:
    setting: str
    accuracy: float
    flushes: int
    warnings: int


def experiment(seed: int, llm: LLM) -> tuple[list[Row], list[str]]:
    data = generate(seed)
    agent = MemGPTAgent(llm, ctx_tokens=120)
    n_calls = 0
    for t in data.all_turns():
        if t.speaker == "user":
            n_calls += len(agent.step(t.text, t.ts))
    ok = 0
    for q in data.questions:
        arc = agent.archival.search(q.question, 5)
        ev = [agent.arc_texts[d] for d, _ in arc]
        toks = set(q.question.lower().split())
        ev += [m.text for m in agent.fifo
               if toks & set(m.text.lower().split())][:3]
        pred = answer_with_evidence(llm, q.question, ev)
        ok += judge_answer(llm, q.question, q.gold, pred)
    rows = [Row("MemGPT", ok / len(data.questions), agent.flushes,
                agent.warnings)]
    # PT: baseline de comparação (mesma métrica). EN: baseline comparison.
    from papers.common.memory_api import FullContextMemory
    base = FullContextMemory(max_tokens=200)
    for t in data.all_turns():
        base.add(MemoryItem(t.text, t.ts))
    ok = sum(judge_answer(llm, q.question, q.gold,
                          answer_with_evidence(llm, q.question,
                                               base.retrieve(q.question,
                                                             k=8)))
             for q in data.questions)
    rows.append(Row("FullContext (truncated)", ok / len(data.questions), 0, 0))
    return rows, FUNCTIONS


def render(rows: list[Row], fns: list[str]) -> str:
    lines = ["# RESULTS — p10 MemGPT", "",
             "Generated by `python -m papers.p10_memgpt.run --write-results` "
             "(fixed seed, MockLLM). Demonstrates the mechanism offline — "
             "does NOT reproduce the paper's numbers.", "",
             f"Function set (7): {', '.join(fns)}", "",
             "| setting | accuracy | flushes (100%) | warnings (70%) |",
             "|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r.setting} | {r.accuracy:.2f} | {r.flushes} | "
                     f"{r.warnings} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, seed=args.seed)
    rows, fns = experiment(args.seed, llm)
    out = render(rows, fns)
    print(out)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(out,
                                                          encoding="utf-8")


if __name__ == "__main__":
    main()
