"""PT: experimento do p10_memgpt — MemGPT no dataset conversacional
(multi-persona): acurácia por tipo de pergunta + contagens de
warning/flush (70%/100%) vs baselines + oracle.

EN: p10_memgpt experiment — MemGPT on the multi-persona conversational
dataset: per-type accuracy + warning/flush counts vs baselines + oracle.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from papers.common.conv_data import generate
from papers.common.conv_eval import (
    EvalResult,
    baseline_rows,
    eval_memory,
    render_acc_table,
)
from papers.common.llm import LLM, get_llm
from papers.p10_memgpt.adapter import MemGPTAdapter
from papers.p10_memgpt.method import FUNCTIONS


def experiment(seed: int, llm: LLM) -> tuple[list[EvalResult], list[str]]:
    data = generate(seed)
    agent = MemGPTAdapter(llm)
    r = eval_memory(agent, data, llm, name="MemGPT")
    r.extra = f"{agent.agent.flushes} flushes / {agent.agent.warnings} warnings"
    rows = [r, *baseline_rows(data, llm)]
    return rows, FUNCTIONS


def render(rows: list[EvalResult], fns: list[str]) -> str:
    lines = ["# RESULTS — p10 MemGPT", "",
             "Generated by `python -m papers.p10_memgpt.run --write-results` "
             "(fixed seed, MockLLM). Demonstrates the mechanism offline — "
             "does NOT reproduce the paper's numbers.", "",
             f"Function set (7): {', '.join(fns)}", ""]
    lines += render_acc_table(rows, extra_col="context events")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, seed=args.seed)
    rows, fns = experiment(args.seed, llm)
    out = render(rows, fns)
    print(out)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(out,
                                                          encoding="utf-8")


if __name__ == "__main__":
    main()
