"""Runner p23 — WM em rede recorrente com e sem astrócitos.

Protocolo: cue sustentado no assembly → delay → distrator breve → leitura.
Controle decai; com astrócitos o Ca²⁺ do item cruza o limiar, potencializa
as sinapses do assembly e o item persiste — enquanto o distrator breve
não atinge o limiar e é suprimido.

Protocol: sustained cue on the item assembly → delay → brief distractor →
readout. Control decays; with astrocytes the item's Ca²⁺ crosses the
threshold, potentiates assembly synapses, and the item persists — while
the brief distractor never reaches the threshold and is suppressed.
"""

import argparse

import numpy as np

from .method import run_batch

SEEDS = list(range(12))
SWEEP_ALPHA = [0.0, 1.5, 3.5, 5.0]


def render(res, sweep):
    lines = [
        "# RESULTS — p23 Working Memory: SNN + astrocytes (Gordleeva 2021)",
        "",
        "Generated by `python -m papers.p23_astrocyte_wm.run --write-results`"
        " (fixed seeds, offline, numpy only). Rate-based SNN-lite with a"
        " slow Ca²⁺-like astrocyte trace potentiating synapses between"
        f" co-active neurons, {len(SEEDS)} seeds.",
        "",
        "## Retenção do item vs distrator / item vs distractor retention",
        "",
        "| variant | item rate | distractor rate | held (item>2·distr) |",
        "|---|---|---|---|",
    ]
    for astro in (False, True):
        r = res[astro]
        name = "with astrocytes" if astro else "control (no glia)"
        lines.append(
            f"| {name} | {r['item']:.3f}±{r['item_std']:.3f} | "
            f"{r['distractor']:.3f} | {r['held']:.2f} |"
        )
    lines += [
        "",
        "## Sweep do ganho astroglial α / α sweep (item rate @ readout)",
        "",
        "| α | item rate | held |",
        "|---|---|---|",
    ]
    for a, r in sweep.items():
        lines.append(f"| {a} | {r['item']:.3f} | {r['held']:.2f} |")
    lines += [
        "",
        "## Leitura / reading",
        "",
        "- Sem glia o item decai abaixo do nível do distrator: a recorrência"
        " sub-crítica não sustenta o padrão.",
        "- Com astrócitos o cue sustentado leva o Ca²⁺ além do limiar →"
        " sinapses intra-assembly potencializadas → item persiste e o"
        " distrator breve (que não cruza o limiar) é suprimido.",
        "- Without glia the item decays to distractor level; the astrocyte"
        " threshold makes only sufficiently sustained inputs persistent —"
        " the paper's distractor-robustness signature.",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    np.random.default_rng(args.seed)
    res = {a: run_batch(a, SEEDS) for a in (False, True)}
    sweep = {a: run_batch(True, SEEDS, alpha=a) for a in SWEEP_ALPHA}
    md = render(res, sweep)
    print(md)
    if args.write_results:
        import pathlib

        out = pathlib.Path(__file__).with_name("RESULTS.md")
        out.write_text(md + "\n")
        print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
