"""PT: p18 Survey — renderiza a taxonomia (forms/functions/dynamics) de
cada implementação p01–p17 + a tabela de distinção vs RAG/context
engineering + mapa ligando os papers.

EN: p18 Survey — renders the taxonomy (forms/functions/dynamics) of each
p01–p17 implementation + the distinction table + the paper map.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from papers.common.catalog import CATALOG
from papers.p18_survey.taxonomy import (
    CLASSIFICATIONS,
    DISTINCTION_ROWS,
)

RESULTS = Path(__file__).parent / "RESULTS.md"


def _map() -> list[str]:
    """PT: mapa de influência entre os papers. EN: influence map."""
    return [
        "CLIN → Reflexion (reflection variants) → MUSE (when to reflect)",
        "MemRL → Memory-R1 (utility-on-memory vs policy-learning)",
        "CER → Voyager (skills) → MUSE-Autoskill (skill lifecycle)",
        "CoALA → Generative Agents → MemGPT → A-MEM → Zep → Mem0 "
        "(chat memory line)",
        "LongMemEval → MemoryAgentBench → LongMemEval-V2 (benchmarks)",
        "Survey (this paper) classifies all of the above",
    ]


def render() -> str:
    lines = ["# RESULTS — p18 Memory Survey (taxonomy of this repo)", "",
             "Generated by `python -m papers.p18_survey.run "
             "--write-results`. Classification is data in `taxonomy.py`, "
             "grounded in papers/common/catalog.py.", "",
             "## Taxonomy per implementation (§3–§5)", "",
             "| folder | paper | form | functions | dynamics | "
             "justification |",
             "|---|---|---|---|---|---|"]
    for c in CLASSIFICATIONS:
        lines.append(f"| {c.folder} | {c.title} | {c.form} | {c.functions} "
                     f"| {c.dynamics} | {c.justification_en} |")
    lines += ["", "## Memory vs related concepts (§2.3)", "",
              "| concept | what it is | dynamics | distinction |",
              "|---|---|---|---|"]
    for name, what, dyn, dist in DISTINCTION_ROWS:
        lines.append(f"| {name} | {what} | {dyn} | {dist} |")
    lines += ["", "## Paper map", ""]
    lines += [f"- {m}" for m in _map()]
    lines += ["", "## Coverage check", "",
              f"classified: {len(CLASSIFICATIONS)} of "
              f"{len([p for p in CATALOG if p.folder != 'p18_survey'])} "
              "non-survey papers", ""]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    out = render()
    print(out)
    if args.write_results:
        RESULTS.write_text(out, encoding="utf-8")


if __name__ == "__main__":
    main()
