"""PT: experimento do p06_voyager — Voyager no CraftWorld (arXiv 2305.16291).

EN: p06_voyager experiment — Voyager on CraftWorld.

Configurações / Settings:
- full: currículo + skill library + critic (o Voyager completo).
- no-skill-library (ablation): sem retrieval/reuso de skills.
- no-curriculum (ablation): tarefas aleatórias em vez do currículo.
- no-critic (ablation): skills guardadas SEM verificação → biblioteca
  poluída com código quebrado.
- zero-shot: novo episódio com a biblioteca aprendida (generalização, §4.3).

Métricas / Metrics: itens únicos descobertos e índice da iteração em que cada
marco da árvore tecnológica foi alcançado (wooden/stone/iron/diamond).
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from papers.common.llm import LLM, get_llm
from papers.envs.craft import CraftWorld
from papers.p06_voyager.method import milestones, run_episode
from papers.p06_voyager.prompts import CHAIN  # noqa: F401

ITERATIONS = 18
MILESTONES = ["wooden_pickaxe", "stone_pickaxe", "iron_pickaxe", "diamond"]


@dataclass
class Row:
    setting: str
    unique_items: int
    milestone_iters: dict[str, int]
    success_tasks: int
    avg_rounds: float


def experiment(seed: int, llm: LLM) -> list[Row]:
    rows: list[Row] = []
    settings = {
        "full": (True, True, True),
        "no-skill-library": (False, True, True),
        "no-curriculum": (True, False, True),
        "no-critic": (True, True, False),
    }
    learned = None
    for name, (lib, cur, cri) in settings.items():
        env = CraftWorld(target="diamond")
        hist, lib_obj = run_episode(llm, env, ITERATIONS, lib, cur, cri, seed)
        ms = milestones(hist, MILESTONES)
        rows.append(Row(name, len(hist[-1].items), ms,
                        sum(1 for it in hist if it.attempts[-1].success),
                        sum(it.attempts[-1].rounds for it in hist)
                        / max(1, len(hist))))
        if name == "full":
            learned = lib_obj
    # PT: zero-shot generalization (§4.3): env e alvo novos (torch) com a
    # biblioteca aprendida no run 'full' — skills reutilizadas diretamente.
    # EN: zero-shot generalization — fresh env/target (torch) reusing the
    # library learned in the 'full' run.
    env2 = CraftWorld(target="torch")
    hist2, _ = run_episode(llm, env2, 6, True, True, True, seed + 1,
                           library=learned)
    ms2 = milestones(hist2, MILESTONES)
    rows.append(Row("zero-shot (warm library)", len(hist2[-1].items), ms2,
                    sum(1 for it in hist2 if it.attempts[-1].success),
                    sum(it.attempts[-1].rounds for it in hist2)
                    / max(1, len(hist2))))
    env3 = CraftWorld(target="torch")
    hist3, _ = run_episode(llm, env3, 6, True, True, True, seed + 1)
    ms3 = milestones(hist3, MILESTONES)
    rows.append(Row("zero-shot (cold, no library)", len(hist3[-1].items), ms3,
                    sum(1 for it in hist3 if it.attempts[-1].success),
                    sum(it.attempts[-1].rounds for it in hist3)
                    / max(1, len(hist3))))
    return rows


def render(rows: list[Row]) -> str:
    lines = ["# RESULTS — p06 Voyager", "",
             "Generated by `python -m papers.p06_voyager.run --write-results` "
             "(fixed seed, MockLLM). Demonstrates the mechanism offline — "
             "does NOT reproduce the paper's numbers.", "",
             "## Milestone iteration index (0 = never reached)", "",
             "| setting | unique items | tasks solved | avg rounds | " +
             " | ".join(MILESTONES) + " |",
             "|---|---|---|---|" + "---|" * len(MILESTONES)]
    for r in rows:
        lines.append(f"| {r.setting} | {r.unique_items} | "
                     f"{r.success_tasks} | {r.avg_rounds:.2f} | "
                     + " | ".join(str(r.milestone_iters[m])
                                  for m in MILESTONES) + " |")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--llm", default="mock")
    ap.add_argument("--write-results", action="store_true")
    args = ap.parse_args()
    llm = get_llm(args.llm, seed=args.seed)
    rows = experiment(args.seed, llm)
    out = render(rows)
    print(out)
    if args.write_results:
        Path(__file__).with_name("RESULTS.md").write_text(out,
                                                          encoding="utf-8")


if __name__ == "__main__":
    main()
